import { StoreMemberRole } from '../../organizations/enums/organization.enum';
import { Permission } from './permissions.constant';

export const STORE_ROLE_PERMISSIONS: Record<StoreMemberRole, Permission[]> = {
  [StoreMemberRole.OWNER]: [
    Permission.ORGANIZATIONS_READ,
    Permission.STORES_READ,
    Permission.STORES_UPDATE,
    Permission.INVITES_CREATE,
    Permission.INVITES_READ,
    Permission.CATEGORIES_READ,
    Permission.CATEGORIES_CREATE,
    Permission.CATEGORIES_UPDATE,
    Permission.CATEGORIES_DELETE,
    Permission.PRODUCTS_READ,
    Permission.PRODUCTS_CREATE,
    Permission.PRODUCTS_UPDATE,
    Permission.PRODUCTS_DELETE,
    Permission.PROMOS_READ,
    Permission.PROMOS_CREATE,
    Permission.PROMOS_UPDATE,
    Permission.PROMOS_DELETE,
    Permission.ORDERS_CREATE,
    Permission.ORDERS_READ,
    Permission.ORDERS_UPDATE,
    Permission.TRANSACTIONS_READ,
    Permission.TRANSACTIONS_CREATE,
    Permission.TRANSACTIONS_REFUND,
    Permission.ANALYTICS_READ,
  ],
  [StoreMemberRole.MANAGER]: [
    Permission.ORGANIZATIONS_READ,
    Permission.STORES_READ,
    Permission.STORES_UPDATE,
    Permission.INVITES_CREATE,
    Permission.INVITES_READ,
    Permission.CATEGORIES_READ,
    Permission.CATEGORIES_CREATE,
    Permission.CATEGORIES_UPDATE,
    Permission.CATEGORIES_DELETE,
    Permission.PRODUCTS_READ,
    Permission.PRODUCTS_CREATE,
    Permission.PRODUCTS_UPDATE,
    Permission.PRODUCTS_DELETE,
    Permission.PROMOS_READ,
    Permission.PROMOS_CREATE,
    Permission.PROMOS_UPDATE,
    Permission.PROMOS_DELETE,
    Permission.ORDERS_CREATE,
    Permission.ORDERS_READ,
    Permission.ORDERS_UPDATE,
    Permission.TRANSACTIONS_READ,
    Permission.TRANSACTIONS_CREATE,
    Permission.TRANSACTIONS_REFUND,
    Permission.ANALYTICS_READ,
  ],
  [StoreMemberRole.CASHIER]: [
    Permission.STORES_READ,
    Permission.CATEGORIES_READ,
    Permission.PRODUCTS_READ,
    Permission.ORDERS_CREATE,
    Permission.ORDERS_READ,
    Permission.ORDERS_UPDATE,
    Permission.TRANSACTIONS_CREATE,
  ],
  [StoreMemberRole.KITCHEN]: [
    Permission.STORES_READ,
    Permission.CATEGORIES_READ,
    Permission.PRODUCTS_READ,
    Permission.ORDERS_READ,
    Permission.ORDERS_UPDATE,
  ],
};

export const ORG_OWNER_EXTRA_PERMISSIONS: Permission[] = [
  Permission.STORES_CREATE,
];
